### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by LordAttano** [LordAttano/LeiaMod#1]
Tasks marked with a * are essential to complete before the mod can be deployed onto a server.

Basic:
* [ ]  Account based login system (SQLite perhaps?)*.
* [ ]  Base admin system structure*.
* [ ]  Write a cleaner function to handle client commands.
* [ ]  Duel system (Allow people to easily create their own duel types with customizable files)*.
* [x]  Easily adjustable mod name, colours, and symbols*.
* [x]  Function to efficiently handle centerprint messages*.
* [x]  Name system with updated checks for colours and blank names*.
* [x]  Duplicate name check*.

Commands/Features:
* [ ]  Basic tools (kick, ban, teleport, etc.)*
* [ ]  Team management tools (lockteam, shuffleteam, etc.)*
* [ ]  Client commands (info, etc.)*
* [ ]  Emotes (Walkable, etc.)*
* [ ]  Auto Reset feature.*
* [ ]  Auto Exec feature.*
* [ ]  Ban system*.
* [ ]  Map modding.
* [ ]  Word trigger system (for teleports and such)*.
* [ ]  Pause system*.
* [ ]  Stats (tracking, match results)*.
* [ ]  Artificial Intelligence improvements.
* [ ]  Admin chat channel.
* [ ]  Private chat channels.
* [ ]  Unlagged (SaberMod).
* [ ]  Ignore client.
* [ ]  Damage plums.
* [ ]  Dimensions (for duels and other such things).
* [ ]  Updated follow/spectator system (Cycle backwards, aim to follow).
* [x]  Certain items affected by force powers*.
* [x]  Tag protection.
* [x]  Chat protection*.
* [x]  Force immunity.

New modes:
* [ ]  Assault (Team).
* [ ]  Red Rover (Team).
* [ ]  Last Man Standing (Both).
* [ ]  King of the Hill (Both).
* [ ]  Kill Quota (Both).
* [ ]  Arms Race (Both).
* [ ]  Capture the Point (Team).
* [ ]  Man Hunt (Team).
* [ ]  Various modes based on other games.
* [ ]  Customizable arenas with files which people can easily setup themselves.
* [ ]  More to be decided.

**Comment by TriForceX** [comment]
What you have planned for "Ignore client"? only "chat" ignore? 
Maybe a complete ignore would be nice (entity disapear)
